### ISSUE TITLE
mitigate the number of times we tag an image

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#1082]
According to @lavalamp, Workflow clusters in GKE are triggering [this bug](https://github.com/kubernetes/kubernetes/issues/32908). This issue occurs because Workflow will re-tag an image even if no changes were made. We used to do this because we would [inject environment metadata into the image](https://github.com/deis/deis/blob/v1.7.3/controller/registry/private.py#L15-L64) when `deis config:set` was called. Now, we just [inject that environment metadata directly into the k8s manifest](https://github.com/deis/controller/blob/master/rootfs/api/models/app.py#L988-L993), so no image modification is required.

While the upstream bug will eventually get fixed, in the meantime we should investigate how we trigger this bug, and see if there is a way to mitigate this issue.

**Comment by mboersma** [comment]
Doing `kubectl get node -o yaml` on one of the offending clusters shows a long list of re-tagged app images:
```yaml
   - names:
      - gcr.io/google_containers/pause:2.0
      sizeBytes: 350164
    - names:
      - localhost:5555/test-57368379:v3
      - localhost:5555/test-225171282:v3
      - localhost:5555/test-349910451:v2
      - localhost:5555/test-765152779:v2
      - localhost:5555/test-531894577:v2
      - localhost:5555/test-531894577:v3
      - localhost:5555/test-957102600:v2
      - localhost:5555/test-957102600:v3
      - localhost:5555/test-101875602:v2
      - localhost:5555/test-736008182:v2
      - localhost:5555/test-312165996:v2
      - localhost:5555/test-312165996:v3
      - localhost:5555/test-966490384:v2
      - localhost:5555/test-92413502:v2
      - localhost:5555/test-953282707:v2
      - localhost:5555/test-578673730:v4
      - localhost:5555/test-846984163:v2
      - localhost:5555/test-19736339:v3
      - localhost:5555/test-539512357:v2
      - localhost:5555/test-316118051:v2
      - localhost:5555/test-457125150:v2
      - localhost:5555/test-270332264:v2
      - localhost:5555/test-270332264:v3
      - localhost:5555/test-84933414:v2
      - localhost:5555/test-84933414:v3
      - localhost:5555/test-241757411:v2
      - localhost:5555/test-241757411:v3
      - localhost:5555/test-778712360:v2
      - localhost:5555/test-778712360:v3
      - localhost:5555/test-778712360:v4
      - localhost:5555/test-848623511:v3
      - localhost:5555/test-159686861:v2
... [couple thousand lines omitted]
```

So clearly this isn't an immediate problem with Deis Workflow itself; rather it's an artifact of CI running many times and re-tagging similar images.

One approach to try here is garbage-collecting old images and tags when e2e runs. If that approach works out, we should investigate doing something similar within Workflow itself, since it is conceivable a similar problem could happen through normal usage over long periods of time.
