### ISSUE TITLE
Removing a domain when it has a cert attached does not work

### ISSUE THREAD

**Issue by ged15** [deis/controller#1172]
```shell
deis domains:add example.org
deis certs:attach example-org example.org
deis domains:remove exaple.org

kubectl get svc/app -n app -o yaml
```

This outputs:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    router.deis.io/certificates: ""
    router.deis.io/domains: app,example.org
```

This does not happen when the domain being removed does not have a certificate attached.
