### ISSUE TITLE
Missing global settings customization in helm chart

### ISSUE THREAD

**Issue by felixbuenemann** [deis/controller#1301]
There is currently no way to set the following global controller environment variables without customizing helm charts:

* DEIS_DEPLOY_BATCHES
* DEIS_DEPLOY_TIMEOUT
* KUBERNETES_DEPLOYMENTS_REVISION_HISTORY_LIMIT
* KUBERNETES_POD_TERMINATION_GRACE_PERIOD_SECONDS

(Probably more, all of the above can be overridden using the equally named environnment variables in each app.)

It would be great if the controller helm chart had a `environment_variables` section to allow setting these variables, similar to `router.deployment_annotations` in the deis/router chart:

```yaml
controller:
  environment_variables:
    KUBERNETES_DEPLOYMENTS_REVISION_HISTORY_LIMIT: "10"
    KUBERNETES_POD_TERMINATION_GRACE_PERIOD_SECONDS: "60"
```

Alternatively separate values could be added for each setting, but I think this approach is more flexible and avoids the need to document rarely customized settings.
