### ISSUE TITLE
Health Check port mismatch

### ISSUE THREAD

**Issue by helgi** [deis/controller#707]
_From @sstarcher on May 4, 2016 12:14_

Info
This is a Dockerfile that is referencing a parent Dockerfile that has an exposed port of 3000

Steps
* deis create
* git push deis
* deis config:set HEALTHCHECK_URL=/

```
Creating config... done

=== uchiwa Config
HEALTHCHECK_FAILURE_THRESHOLD      3
HEALTHCHECK_INITIAL_DELAY          50
HEALTHCHECK_PERIOD_SECONDS         10
HEALTHCHECK_PORT                   5000
HEALTHCHECK_SUCCESS_THRESHOLD      1
HEALTHCHECK_TIMEOUT                50
HEALTHCHECK_URL                    /
```

The expectation was for the HEALTHCHECK_PORT to be 3000.
A ```kubectl get pods -o yaml --namespace=app``` shows the port is actually correct.
```
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
```

A subsequent deployment still has the correct liveness probe of 3000 while the HEALTHCHECK_PORT is still listed as 5000.

_Copied from original issue: deis/workflow#215_
