### ISSUE TITLE
workers are deployed with a healthcheck

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#879]
For example, deploying example-dockerfile-procfile-http:

```
><> deis scale worker=1
Scaling processes... but first, coffee!
done in 128s
=== www Processes
--- worker:
www-v2-worker-sy6c2 starting (v2)
--- web:
www-v2-web-dp2h0 up (v2)
```

From checking the pod:

```
readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: 80
      timeoutSeconds: 5
```

The worker process does not run the API server, therefore it will always fail the health check. Non-web processes should not have a healthcheck.
